/**
 * toolsHub.test.tsx — SUITE-02 / SUITE-03 tools-hub homepage.
 *
 * The homepage `/` is the instrument-panel tools-hub:
 *   - the Vestaboard is the hero centerpiece (static placeholder this phase),
 *   - below it a grid of ToolCards generated by mapping TOOL_REGISTRY,
 *   - the Sign card routes to /sign; coming-soon cards are visibly marked + inert,
 *   - card count tracks the registry length (single source of truth, SUITE-03).
 *
 * SignRoute (via the registry's Sign element) transitively imports react-pdf's
 * pdfWorker (DOMMatrix at import time, absent in jsdom) — mock it like the
 * signing-flow tests so the registry module imports cleanly.
 */
import { describe, it, expect, afterEach, vi } from 'vitest'
import { render, cleanup } from '@testing-library/react'
import { MemoryRouter } from 'react-router-dom'

vi.mock('react-pdf', () => ({
  Document: () => null,
  Page: () => null,
  pdfjs: { GlobalWorkerOptions: { workerSrc: '' }, version: '0' },
}))
vi.mock('../lib/pdfWorker', () => ({
  default: undefined,
  pdfOptions: { cMapUrl: '/cmaps/', cMapPacked: true, standardFontDataUrl: '/standard_fonts/' },
}))

import { ToolsHub } from '../components/ToolsHub'
import { TOOL_REGISTRY } from '../tools/registry'

afterEach(() => cleanup())

function renderHub() {
  return render(
    <MemoryRouter>
      <ToolsHub />
    </MemoryRouter>,
  )
}

describe('SUITE-02: tools-hub homepage', () => {
  it('renders the Vestaboard hero centerpiece (documents-processed label)', () => {
    const { getByLabelText } = renderHub()
    expect(getByLabelText(/documents processed/i)).toBeTruthy()
  })

  it('renders one tool card per TOOL_REGISTRY entry (SUITE-03)', () => {
    const { container } = renderHub()
    const cards = container.querySelectorAll('[data-tool-card]')
    expect(cards.length).toBe(TOOL_REGISTRY.length)
  })

  it('renders every tool name from the registry', () => {
    const { getByText } = renderHub()
    for (const tool of TOOL_REGISTRY) {
      expect(getByText(tool.name)).toBeTruthy()
    }
  })

  it('the Sign card is a link to /sign', () => {
    const { container } = renderHub()
    const signCard = container.querySelector('[data-tool-card="sign"]')
    expect(signCard).not.toBeNull()
    const link = signCard!.closest('a') ?? signCard!.querySelector('a')
    expect(link).not.toBeNull()
    expect(link!.getAttribute('href')).toBe('/sign')
  })

  it('every coming-soon card (if any) is marked COMING SOON and is not a navigation link', () => {
    // As of 12-01 the registry has no coming-soon entries (pdf-to-image resolved the
    // last one); this loop is a no-op when the set is empty and still pins the
    // marked + inert contract for any future coming-soon tool.
    const { container } = renderHub()
    const comingSoon = TOOL_REGISTRY.filter((t) => t.status === 'coming-soon')
    for (const tool of comingSoon) {
      const card = container.querySelector(`[data-tool-card="${tool.id}"]`)
      expect(card, `card for ${tool.id}`).not.toBeNull()
      expect(card!.textContent).toMatch(/coming soon/i)
      // Inert: not wrapped in / containing an anchor.
      expect(card!.closest('a')).toBeNull()
      expect(card!.querySelector('a')).toBeNull()
    }
  })

  it('keeps the hub-stub testid so the SUITE-01 router proofs stay green', () => {
    const { container } = renderHub()
    expect(container.querySelector('[data-testid="hub-stub"]')).not.toBeNull()
  })

  it('renders the founder note (relocated from /sign) below the grid', () => {
    const { getByText } = renderHub()
    expect(
      getByText(/I built this because I couldn't find a PDF signer that was actually free/),
    ).toBeTruthy()
  })
})
