/**
 * ToolsHub.tsx — SUITE-02 tools-hub homepage (`/`), the new front door.
 *
 * Layout (instrument-panel brand: warm bone surfaces, Signal Orange accent,
 * mono chrome):
 *   - a slim brand header carrying the <Wordmark /> + a link to /tools;
 *   - the HERO: the <Vestaboard /> documents-processed counter as the headline
 *     visual centerpiece (static placeholder this phase; Phase 13 wires it live);
 *   - below the hero, a responsive grid of <ToolCard />s generated by mapping
 *     TOOL_REGISTRY (SUITE-03 — adding a tool = adding one registry entry, no
 *     edit here);
 *   - the shared <LandingFooter /> for footer continuity.
 *
 * Carries `data-testid="hub-stub"` so the SUITE-01 routing proofs (routing.test
 * asserts the `/` + catch-all render contains the hub) stay green after the
 * 10-01 stub is replaced.
 */
import { Link } from 'react-router-dom'
import { TOOL_REGISTRY } from '../tools/registry'
import { Vestaboard } from './Vestaboard'
import { ToolCard } from './ToolCard'
import { Wordmark } from './Wordmark'
import { LandingFooter } from './LandingFooter'
import { HeroSection } from './HeroSection'

export function ToolsHub() {
  return (
    <div
      data-testid="hub-stub"
      style={{
        minHeight: '100dvh',
        display: 'flex',
        flexDirection: 'column',
        backgroundColor: 'var(--color-surface)',
      }}
    >
      {/* Brand header */}
      <header
        style={{
          height: '56px',
          backgroundColor: 'var(--color-surface-elevated)',
          borderBottom: '1px solid var(--color-line-strong)',
          padding: '0 16px',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
        }}
      >
        <Wordmark />
        <Link
          to="/tools"
          style={{
            fontFamily: 'var(--font-mono)',
            fontSize: '11px',
            fontWeight: 600,
            letterSpacing: '0.12em',
            textTransform: 'uppercase',
            color: 'var(--color-ink-muted)',
            textDecoration: 'none',
          }}
        >
          All tools →
        </Link>
      </header>

      <main style={{ flex: 1 }}>
        {/* HERO — the vestaboard counter is the centerpiece headline visual. */}
        <section
          style={{
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            textAlign: 'center',
            gap: '20px',
            padding: '64px 16px 48px',
          }}
        >
          <p
            style={{
              fontFamily: 'var(--font-mono)',
              fontSize: '14px',
              fontWeight: 700,
              letterSpacing: '0.2em',
              textTransform: 'uppercase',
              color: 'var(--color-ink-muted)',
              margin: 0,
            }}
          >
            The free, private PDF toolkit
          </p>

          <Vestaboard />

          <p
            style={{
              maxWidth: '560px',
              fontFamily: 'var(--font-sans)',
              fontSize: '16px',
              lineHeight: 1.5,
              color: 'var(--color-ink-muted)',
              margin: 0,
            }}
          >
            Sign, merge, and organize your documents right in your browser. Nothing
            is ever uploaded — your files never leave your device.
          </p>
        </section>

        {/* Tool grid — generated from the registry (SUITE-03). */}
        <section
          aria-label="Tools"
          style={{
            maxWidth: '880px',
            margin: '0 auto',
            padding: '0 16px 64px',
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fill, minmax(220px, 1fr))',
            gap: '16px',
          }}
        >
          {TOOL_REGISTRY.map((tool) => (
            <ToolCard key={tool.id} tool={tool} />
          ))}
        </section>

        {/* Founder note — the "why I built this" hero, relocated from /sign to
            live on the landing page below the tool grid, above the footer. */}
        <HeroSection />
      </main>

      <LandingFooter />
    </div>
  )
}
